### ISSUE TITLE
GrazeRSS crashes on 9.0 Pie

### ISSUE THREAD

**Issue by BenjaminHCCarr** [travistabbal/GrazeRSS#36]
Just upgraded to AOSP based Pie on Essential Phone PH-1

Here are my bugs:

1. `Open in browser` crashes `GrazeRSS`
2. `Share item...` crashes `GrazeRSS`

This doesn't happen in other apps, and it crashes such that the framework doesn't pop up a report dialog.

Related #35

Is there a log that would be useful @travistabbal?

**Comment by BenjaminHCCarr** [comment]
Refining what causes the error:
After clearing caches, and resetting everything to scratch.
I can now reproduce the crash only by:

1. `Open in Browser` from the RSS list crashes `GrazeRSS`
1a. `Open in browser` from article works fine
2. `Share item...` crashes `GrazeRSS` regardless of where it is called from

**Comment by novoid** [comment]
I can confirm similar behavior of GrazeRSS v2.0.10 on OnePlus5 with the latest upgrade to Android 9: `OnePlus5Oxygen_23_1812232102`

Description:

- article overview: "Show in browser": -> no browser displayed in share dialog; when I share to my email client instead, I get:

```
Sorry!

GrazeRSS hit a wall. Please send this mail, so that the developer can analyze/fix the issue.
If it is not too much to ask, please add to this mail what you just did between the following lines:

-------


-------
-- Time: Thu Jan 03 16:06:28 GMT+01:00 2019
-- Android Version: sdk=28, release=9, inc=1812232046
-- Memory free: 0.77MB total: 18.71MB max: 256.00MB
-- BuildD: ONEPLUS A5000_23_181223
-- Manufacturer: OnePlus
-- Device: OnePlus5
-- Model: ONEPLUS A5000
-- NewsRob Version: 2.0.10/210
-- Configured Capacity: 1000
--        Keep Starred: 200
--        Keep Shared: 5
--        Keep Notes: 5
-- Current Article Count: 172
-- Action Bar Location: top
-- Days installed: 488
-- Orientation: 0
-- StorageAdapter: PhoneMemoryStorageAdapter
--   MB available: 4752
-- Phone Memory MB available: 4752.0
-- Sync Auto enabled: false
--      Unread Only: true
--      Delete Read: true
--      NewsRob only: false
--      Offline use: yes
--      Offline Def: 2
-- FireModelUpdate in progress: false
-- LastActivity: ShowArticleActivity.
-- Stacktrace:(1516)
android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
	at android.app.ContextImpl.startActivity(ContextImpl.java:915)
	at android.app.ContextImpl.startActivity(ContextImpl.java:891)
	at android.content.ContextWrapper.startActivity(ContextWrapper.java:379)
	at android.content.ContextWrapper.startActivity(ContextWrapper.java:379)
	at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:159)
	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:923)
	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:913)
	at com.android.internal.view.menu.MenuDialogHelper.onClick(MenuDialogHelper.java:166)
	at com.android.internal.app.AlertController$AlertParams$3.onItemClick(AlertController.java:1169)
	at android.widget.AdapterView.performItemCl
```

- article overview: "Share link": GrazeRSS crashes
- article view: context menu: "Show in Browser" crashes app
- article view: context menu: "Share link" crashes app

This makes GrazeRSS useless to many of my use-cases where I need to share articles to browser or to my notes app.

**Comment by dasty** [comment]
I can confirm exactly same crashes as described above also on Android 10 on Pixel 3A.

**Comment by novoid** [comment]
>  Latest commit 010a300 on Dec 27, 2015 

This project seems to be unmaintained, unfortunately.

Meanwhile, I completely switched to the Android app of http://newsblur.com/ which provides the same set of features (and more). I had to invest some work on finding out about the different usage patterns but I could find a replacement for all GrazeRSS features. No complaints so far.

I recommend you to switch to a different RSS aggregator client as well.
